### ISSUE TITLE
newsletter-inlined - padding in mobile view

### ISSUE THREAD

**Issue by regisaberbache** [leemunroe/htmlemail#10]
More of an enhancement request, I'm working with the newsletter-inlined template, and I'm wondering if it would be possible, in mobile view, to have a 10px padding on the content blocs, just like on the main visual. On desktop all the blocs are perfectly aligned, so nothing to change there.
I hope this attached picture will make up for my poor explanation :

![padding](https://user-images.githubusercontent.com/10544627/33956468-eb7e71b2-e03e-11e7-9b3a-a31eb11e4578.jpg)

If that kind of request doesn't belong on github, I will gladly write an email.

**Comment by leemunroe** [comment]
@regisaberbache Thanks for the request. Makes sense. Is your goal to have consistency? I'm curious why you'd like to add 10px to the blocks as opposed to removing the 10px from the main visual.

Also, do you need help accomplishing this with the current templates? If you want to share your code privately I can take a look. Email hello@htmlemail.io

**Comment by regisaberbache** [comment]
@leemunroe Thank you for the answer. Looks like I didn't try hard enough before opening my issue, after playing more with the @media CSS I finally got what I wanted. I was indeed looking for consistency on mobile, and like how a 10px padding all around make my emails feel less cluttered.
Issue solved on my end. Thanks for those great templates !
