### ISSUE TITLE
Instructions / source to use with grunt-email-workflow

### ISSUE THREAD

**Issue by tleyden** [leemunroe/htmlemail#11]
It would be useful to include source files and instructions compatible with https://github.com/leemunroe/grunt-email-workflow/

I was able to get the examples from grunt-email-workflow working with Mailgun and the uploading images to an s3 bucket, however it's not clear how to use the templates with htmlemail.io in conjunction.

**Comment by leemunroe** [comment]
@tleyden Sorry for the late response. Agreed it would be helpful to include developer source files like Grunt and SCSS files. I hope to introduce this at some point.

**Comment by leemunroe** [comment]
The SCSS files are now available as part of our developer package.
https://htmlemail.io/
