### ISSUE TITLE
How to use it with Nodejs Mailgun module

### ISSUE THREAD

**Issue by omarojo** [leemunroe/htmlemail#15]
How should we use this templates but with Nodejs ?
Im using mailgun module, which sends the email using a simple .send(data) method.
and data... has everything on it including the HTML string. 

am I suppose to copy and paste a huge HTML string from your templates in that variable ?

**Comment by leemunroe** [comment]
@omarojo Can you link to the module you're using? Yes, the quick way would be copy/paste the HTML into a huge string like you say. With some more time you could build out a directory structure so your app pulls in the template you need and injects the variables. I don't have a personal example to share but something like https://github.com/niftylettuce/email-templates
