### ISSUE TITLE
Is there an API for this?

### ISSUE THREAD

**Issue by djcarter85** [leemunroe/htmlemail#16]
First off, great tool! Really useful.

Is there an API I can call? I want to automate something and it would be really useful to be able to call a web API rather than having to manually copy stuff across.

**Comment by leemunroe** [comment]
@djcarter85 There is no API but you can set them up to use with other tooling e.g. this grunt CLI tool I open sourced https://github.com/leemunroe/grunt-email-workflow

**Comment by djcarter85** [comment]
OK thanks.
