### ISSUE TITLE
Welcome-embeded.html email rendering issues

### ISSUE THREAD

**Issue by marian-gheorghe** [leemunroe/htmlemail#17]
The welcome-embeded.html template is not working well with Outlook Office 365 (desktop, windows 10) Only the text styles seem to be rendered, borders and background colors are not. 
Email Service - SMTP MailGun

Email: Outlook view
![outlook_view](https://user-images.githubusercontent.com/39998360/49555746-43a57300-f901-11e8-8098-c3862d69dd96.png)

Email: Gmail view (almost there, but it's missing the horizontal lines between sections, see Html in browser view)
![gmail_view](https://user-images.githubusercontent.com/39998360/49555779-6afc4000-f901-11e8-82b2-32f1d111c74d.png)

Html in browser view
![html_inbrowser_view](https://user-images.githubusercontent.com/39998360/49555857-b6165300-f901-11e8-9107-fece9c004512.png)

**Comment by leemunroe** [comment]
@marian-gheorghe Thanks for the screenshots. Can you confirm if you are inlining the CSS before sending? If not can you try that? A lot of clients (specifically Outlook) need CSS inlined to work.

[More information here](https://github.com/leemunroe/htmlemail#working-with-inline-css) and we have a [CSS Inliner](https://htmlemail.io/inline/) if you need to use it.

Note: Mailgun does not inline CSS automatically.

**Comment by marian-gheorghe** [comment]
Hi, thanks for the quick reply. I have now used the welcome-inline.html and it's working, there is still a small issue in Outlook with the spacing 

![image](https://user-images.githubusercontent.com/39998360/49579135-be937b80-f94b-11e8-815e-88646b3a5469.png)

For Gmail this looks great

![image](https://user-images.githubusercontent.com/39998360/49579360-4b3e3980-f94c-11e8-870a-3d6ead319820.png)

**Comment by leemunroe** [comment]
@marian-gheorghe Ok great! Nearly there.

The Outlook margin issue is a bug, I was able to reproduce. Thanks for the report. I'll need to go back and update these. In the meantime what you need to do is move the `padding-top:24px` style from the footer div and apply this to the first table cell instead i.e.
```
<td class="content-block" style="font-family: Helvetica, sans-serif; vertical-align: top; padding-top: 24px; padding-bottom: 24px; font-size: 12px; color: #999999; text-align: center;" valign="top" align="center">
```
