### ISSUE TITLE
Outlook 2016 content not centered in receipt-inlined.html

### ISSUE THREAD

**Issue by zacrubin** [leemunroe/htmlemail#18]
Hello,

I have Microsoft Outlook 2016 via an O365 subscription running on Windows 10. I'm using the default receipt-inlined.html template and the Order Summary section is left aligned. I'm using AWS SES to send emails. Any ideas?

Thanks,

Zac

**Comment by leemunroe** [comment]
@zacrubin Hey Zac, I ran the receipt through Litmus on all the Outlooks and couldn't replicate the issue.
https://litmus.com/checklist/emails/public/d758379

Can you confirm you didn't change the HTML at all? And can you provide a screenshot?

I'll dig in a bit more.

**Comment by zacrubin** [comment]
Lee,

I'll try to grab a screenshot later today. The HTML was not changed.

Thanks,

Zac

**Comment by zacrubin** [comment]
PS: The receipt-inlined.html I downloaded looks different than the one you show in the litmus link.
