### ISSUE TITLE
Outlook 2013

### ISSUE THREAD

**Issue by jenc2019** [leemunroe/htmlemail#19]
Hi! I love your templates, they're great to work with! I used the ecommerce template, and it looks good in my emails, except in Outlook 2013 on windows 10. On my desktop, it is shifting to one column, as if it is a mobile screen. I don't know why. Would you mind looking at it to see if you can pinpoint the issue? i saw a previous issue that seemed similar, but I don't have the ode you referenced I don't think. How can I share my email code with you privately?

**Comment by leemunroe** [comment]
@jenc2019 Hey sorry to hear you're having issues.

1) Can you share a screenshot here of how it looks?

2) Can you confirm the CSS is being inlined before you're sending it?

2) Can you email me the code hello@htmlemail.io? You can use https://codeshare.io to share the code

Thanks

**Comment by leemunroe** [comment]
Followed up offline. Issue with ESP (ReadyTalk) stripping HTML.
