### ISSUE TITLE
Gmail app not responsive?

### ISSUE THREAD

**Issue by danielusername** [leemunroe/htmlemail#2]
Hi - I have purchase your templates today, and found that the newsletter template does not collapse in the gmail app - I have hosted the images, and I am using an the inlined version. Am I doing something wrong? Thanks! 

![18366_134602](https://cloud.githubusercontent.com/assets/20956644/17568732/f11b81ea-5f12-11e6-80ea-daf58812e5ac.png)

**Comment by danielusername** [comment]
Hi - Im still not having any luck with the gmail app :( Is it possible I am doing something wrong?

**Comment by leemunroe** [comment]
Hey @danielusername thanks for emailing me directly with the details. Responding here too for transparency. 

Correct Gmail columns should stack as [previewed here](https://litmus.com/checklist/emails/public/625ca9a) (for Android). Hopefully we've got to the bottom of the iPhone issue.

**Comment by danielusername** [comment]
Thank you so much!! :) Really great templates and a quick response for my issue. Thanks again @lee_munroe.

**Comment by leemunroe** [comment]
Update: This feature should be fixed ([see preview](https://litmus.com/checklist/emails/public/fb2f994)). Will push an update shortly. Looking into another issue with Android header styling.

**Comment by leemunroe** [comment]
Fixed. Latest files available via Gumroad. https://litmus.com/checklist/emails/public/0da318a

**Comment by danielusername** [comment]
Amazing! Thanks again for your diligence and quick responses.

Where can I download the latest versions?

Youre the man. Thanks again


PS – do you know if they work with ‘whatcounts’? – not a big deal

Daniel Sivan

**Comment by leemunroe** [comment]
@danielusername Hey Daniel, you should have received an update from Gumroad with a link to the latest version. As it's a paid product you'll need your Gumroad credentials to access. If you're having issues email me hello@htmlemail.io

**Comment by danielusername** [comment]
Will do. Thanks!
