### ISSUE TITLE
Having Trouble Uploading Zip file from Mac to Mailchimp 

### ISSUE THREAD

**Issue by EmmaHous** [leemunroe/htmlemail#4]
![screen shot 2016-11-17 at 4 17 27 pm](https://cloud.githubusercontent.com/assets/23516323/20377274/343c34ac-ace2-11e6-9952-35fd69a6684a.png)
Getting an error message.

**Comment by leemunroe** [comment]
Sorry to hear that @EmmaHous let's figure out what's going on.

What error message are you getting exactly? Maybe I'm blind but I'm failing to see it in the screenshot provided.

**Comment by EmmaHous** [comment]
No problem!   Thanks for helping me.

It says we have detected a spike.   You should take action.   In the 
code it says "something went wrong" :)

I will give you the steps

1.  Downloaded ZIP file to Apple Mac downloads V 10.11.16
2.  Opened Mailchimp
3.  Upload ZIP file to Templates Create Your Own Code
4.  Error message

Emma

**Comment by leemunroe** [comment]
Ah I see. This is actually part of the example email template :)

**Comment by leemunroe** [comment]
@EmmaHous On closer inspection looks like you can only upload one template at a time with Mailchimp, which may also be adding to the confusion. For each template the best approach is to create a new HTML template in Mailchimp, then copy the code across for each template. I realize this is a bit of a longer process than a simple zip upload. Happy to help or provide you with individual zip files for each template.

**Comment by EmmaHous** [comment]
On 2016-11-19 07:41, Lee Munroe wrote:
> @EmmaHous [1] On closer inspection looks like you can only upload one
> template at a time with Mailchimp, which may also be adding to the
> confusion. For each template the best approach is to create a new HTML
> template in Mailchimp, then copy the code across for each template. I
> realize this is a bit of a longer process than a simple zip upload.
> Happy to help or provide you with individual zip files for each
> template.
> 
Yes please, if it isn't too much trouble, that will be very helpful.   
Am I allowed to use the templates on multiple Mailchimp accounts?     I 
have three projects on right now and each could use your magic 
templates.

Emma

**Comment by leemunroe** [comment]
@EmmaHous No problem. Email me hello@htmlemail.io and I'll zip them individually for you. If you could let me know which of the templates you want to use in Mailchimp even better.
