### ISSUE TITLE
Icons need to be replaced

### ISSUE THREAD

**Issue by mwujek** [leemunroe/htmlemail#5]
Here's a list of the images/icons that are out of date:

googleplus.png
googleplus-alt.png
instagram.png
instagram-alt.png
playstore.png

**Comment by leemunroe** [comment]
@mwujek Thanks for the heads up. On it.

**Comment by mwujek** [comment]
@leemunroe I needed these for a project today. I packaged them for you if you haven't had the time to do this already. I used #fff and #000 at 20% opacity. https://www.dropbox.com/s/ici5r1340oqegms/icons-email.zip?dl=0

**Comment by leemunroe** [comment]
@mwujek Awesome, thanks for doing that. Updated the zip file available on Gumroad and will send an update shortly.

**Comment by mwujek** [comment]
@leemunroe No problem!
