### ISSUE TITLE
Template issue in Outlook App Android (e.g. Nougat)

### ISSUE THREAD

**Issue by kladiv** [leemunroe/htmlemail#7]
Hello,
i found a buttons template issue when emails are view in Outlook App:

![screenshot_20170614-134154](https://user-images.githubusercontent.com/1803926/27137161-7e9e3eb6-511d-11e7-8460-8fd628116cce.png)

Can you check please?
Thank you

**Comment by leemunroe** [comment]
Thanks @kladiv. Is this using the inlined CSS version?

**Comment by kladiv** [comment]
Hi @leemunroe, yes the inlined

**Comment by leemunroe** [comment]
Thanks @kladiv. I'm struggling to troubleshoot this as Litmus doesn't support Outlook for Android, nor do I have an Android phone handy for testing. So bear with me as I read through some issues online.

[This article](https://litmus.com/community/discussions/6012-outlook-com-email-app-no-longer-responsive-android) seems to imply it depends what email it is you're using. Can you confirm if you're using a @outlook.com or @live.com or something else?

[This article](http://www.courtneyfantinato.com/email-rendering-outlook-app/) has the same suggestions and actually goes in to more detail with tests, an unfortunately no one seems to have a solution.

**Comment by leemunroe** [comment]
@kladiv Thanks. Unfortunately I'm not sure what can be done at this time. Seems to be an issue with Outlook on Android that hasn't been solved. If you don't mind testing a bit more can you try the following:

1. If you send [this template](https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html) do you get the same results?
2. If you send the email to a Yahoo or AOL email address do you get the same results?

Of the users you're sending emails to do you know how many use this client?

**Comment by leemunroe** [comment]
@kladiv Outlook has made some updates recently that "fix" a lot of issues. Can you confirm if this is fixed now? https://litmus.com/blog/consistent-media-query-support-returning-to-outlook-apps

**Comment by kladiv** [comment]
@leemunroe Hi, yes issue has been solved
Thank you
