### ISSUE TITLE
Outlook / Mail for Windows 10

### ISSUE THREAD

**Issue by iantearle** [leemunroe/htmlemail#8]
![img_2899](https://user-images.githubusercontent.com/201174/28859980-74963332-7752-11e7-8dfc-85882add2c51.PNG)

Have an issue with outlook or mail for windows 10, I'm trying to get the version etc but it looks like the main content area isn't wide enough??

**Comment by iantearle** [comment]
![img_2900](https://user-images.githubusercontent.com/201174/28860071-e01ab07e-7752-11e7-96b6-d19a2dfb0313.PNG)

**Comment by leemunroe** [comment]
@iantearle Sorry for delayed response. Looking into this now.

**Comment by leemunroe** [comment]
@iantearle Trying to reproduce this. I don't have direct access to Outlook 10 I'm afraid but I'm using Litmus to test. This is what I see when I test the plain email template (which I think you're using), which is different to your screen shot.

![image](https://user-images.githubusercontent.com/15963/29050713-a01a413a-7b92-11e7-8c94-f75ad8e58716.png)

1. Are you using the version with CSS inlined?
2. What ESP are you using to send the email?
3. Can you share the full code you're sending? (email hello@htmlemail.io if you'd prefer not to share here)

Thanks

**Comment by leemunroe** [comment]
@iantearle Thanks for that. If you're able to reproduce the code that would be good. My thinking is it is likely a missing closing tag or something to do with the Outlook conditional statements. 

Although before you do that, do you have access to this version of Outlook? If you could send the original inlined email to see what results you get that would help us see if Litmus is showing the same thing. You can [use this code as a test](https://raw.githubusercontent.com/leemunroe/responsive-html-email-template/master/email-inlined.html).

**Comment by leemunroe** [comment]
Figured out what this issue was. 

Remove `width: auto !important` from `.container` class. If this is left embedded in the head then it causes issues in Outlook. 

Will be sending out an email shortly via Gumroad with updated templates.

@iantearle Thanks for reporting.
